### ISSUE TITLE
Load average is multiplied by 100 for some reason

### ISSUE THREAD

**Issue by mpe** [hungryblank/gosysstatsd#1]
You multiply the load average by 100 for some reason. I don't understand why?

You need to document that at least, it makes it confusing when trying to interpret the load numbers. My load average of 12,500 was worrying me for a minute :-)

**Comment by hungryblank** [comment]
It's multiplied by 100 to make it a integer value for statsd.

**Comment by hungryblank** [comment]
I amended the text in the Readme.md in b21af2d8bd9ab2ed9dbc40cab9388647a092a612

**Comment by mpe** [comment]
Ah right, I don't know statsd that well but that makes sense. Thanks.
